apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: ibrademe/my_mysql_image
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: fil_rouge
            - name: DATABASE_USER
              value: root
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 3306
