apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30101 # Port NodePort
      targetPort: 80
  type: NodePort # Type de service
